### ISSUE TITLE
audioloop with ecasound not working 

### ISSUE THREAD

**Issue by hamez99** [moviemasher/moviemasher.rb#12]
I was trying to get a short audio clip played over a longer video on a loop for the duration of the video.  I found that the commands for ecasound that moviemasher was generating where using the clip's "Frames" parameter for both the "select" and "-t" options.
I was able to fix it by changing line 254 of shell_helper.rb in my copy to 
 audio_cmd += ",#{graph[:duration]},#{graph[:waved_file]}".

It seems what is needed for the "select" option on the ecasound input is the duration of the input clip and the -t needs to be the total time you want it to loop which would be determined by the "Frames" parameter of the clip.

**Comment by syntropo** [comment]
Thanks very much for the bug report and fix

**Comment by syntropo** [comment]
This has been fixed in version 4.0.25
