### ISSUE TITLE
JSON job documentation for AWS-SQS

### ISSUE THREAD

**Issue by olivier-jaber** [moviemasher/moviemasher.rb#13]
Hello.

I have an AWS EC2 node setup with moviemasher.rb that accepts mash jobs via SQS, however I am having difficulty determining the exact JSON instructions that will mash video clips in the format that I require. I've included the JSON job that I'm currently using for context. I'm trying to get video clips of various dimensions (portrait/landscape) to be zoomed and cropped to fit the output video's dimensions and have crossfade transitions between clips. The current documentation for moviemasher data structures does not explain how the various parts should be used together nor how to generate JSON mashing instructions.

[mash_instructions.txt](https://github.com/moviemasher/moviemasher.rb/files/977139/mash_instructions.txt)

Any assistance in solving my particular problem or referral to resources for programmatically generating mashing instructions is appreciated.

Thank you.

**Comment by gotenks2013** [comment]
There isnt any such documentation even though there really should be.  The recurring recommendation from the developers is to look at the code documentation and the code.  I had to get creative and capture some output from the angular version before moviemasher.rb picked it up and reverse engineer from there while referencing the documentation.
A couple of things that help:
The JSON mostly represents the ruby objects.   All the ruby code is doing is taking the json and the referenced input files and transforming that into a series of ffmpeg and ecasound commands to get the desired output.  In the json file, for transitions and effects, if you look at the ffmpeg filter documentation you will see that you are really just defining some filters in those ffmpeg commands.  Parameters and names match up one for one.
Also, the ruby code implements some logic for defining parameters and evaluating expressions for things like filters within the json file along with some helper functions.
In my project I basically just fiddled with the captured json file until i was able to get it to do what i wanted in general and then wrote the code to generate it with any variable parameters.
