### ISSUE TITLE
S3 Sequence very slow

### ISSUE THREAD

**Issue by ngivoni** [moviemasher/moviemasher.rb#14]
D,

We recently moved over from using HTTP to S3 as the type for our image sequencing. The HTTP would return in a quick burst, but the S3 seems to just trickle in where a *.JPG file shows up every minute or so...what is the cause of the delay and how can we fix it.  It's obviously unacceptable to have it so slow. 
`local["job"]["outputs"] = [{
						"type": "sequence"
						,"video_rate": 10
						,"quality": 1
						,"extension": "jpg"
						,"dimensions": "256x144"
					}];`

**Comment by syntropo** [comment]
I'm not sure what the cause of the problem would be. Is the bucket in a different region? Is it really an S3 bucket, or a CloudFront distribution? Those can be slower.
