### ISSUE TITLE
Feature: specify offset for image outputs

### ISSUE THREAD

**Issue by conor-mac-aoidh** [moviemasher/moviemasher.rb#4]
I've been trying to generate a thumbnail for a video using moviemasher. I have a video input and a number of outputs. Specifying an image output for the video does produce the thumbnail, but it is always taken from the start of the video (which is usually blank). It would be very useful if you could set the 'offset' in seconds for an image output (using `ffpmeg -ss`):

```javascript
           {
               "path": "path/to/dir",
               "name": "thumb",
               "extension": "png",
               "dimensions": "80x60",
               "quality": 1,
               "offset": 3,
               "required": true,
               "type": "image"
           }
```

Or maybe this is already possible using some other property?

Thanks

Conor

**Comment by syntropo** [comment]
Currently only inputs support the offset option - the ability to trim outputs was removed in 4.x because it was overly complicating things. So, this could only be done as a separate job from the other outputs that utilize the whole video. Even then, I'm not sure this would work - please let me know either way.

**Comment by conor-mac-aoidh** [comment]
I'd like to avoid using a second job if at all possible.. I don't exactly want to trim the output, just to pass some extra arguments to ffmpeg when generating the image. Ideally something like this:

```javascript
           {
               "path": "path/to/dir",
               "name": "thumb",
               "extension": "png",
               "dimensions": "80x60",
               "quality": 1,
               "offset": 3,
               "frames" : 1,
               "required": true,
               "type": "image"
           }
```

In ffmpeg it would look like this:

```
ffmpeg -ss 3 -i input_video.mp4 -vframes 1 -s 80x80 thumb.png
```

`frames` specifies the number of image snapshots to take, and `offset` the time to start taking snapshots. Maybe this would be better for just the image sequence type? Then I could set `frames = 1` to generate a thumbnail.

**Comment by syntropo** [comment]
Yeah, we've also removed the ability to add anything before the input. I believe you can still add switches to the existing ones, but they are all related to output for outputs. Support for offset would be ideal, then values like 50% could be specified instead of relying on hard coded time values.

**Comment by conor-mac-aoidh** [comment]
Yes, support for offset, even just for this use-case (TypeImage) would be fine.

**Comment by syntropo** [comment]
This new `offset` output parameter is now supported.
