### ISSUE TITLE
Reproducable duration issues with some videos

### ISSUE THREAD

**Issue by conor-mac-aoidh** [moviemasher/moviemasher.rb#5]
Quite a lot of video files fail to render with MovieMasher due to duration issues. Roughly 10% of the videos I'm rendering with MM are failing with errors like:

```
generated file with incorrect duration 60.49 !=  or 60.51 /tmp/moviemasher/render/dd940ca0-dcd1-0132-fcae-22000b2417a1/dd948c10-dcd1-0132-fcb3-22000b2417a1.mp4
```

I'm not sure what causes this. It is possible to tune this duration check with a `precision` parameter. But, whatever value is given to `precision`, this check will always fail sometimes.

I would like to know why these duration problems are happening. But, in the interim it would be good to have the option to disable this check completely. For users, it results in renders failing all over the place when in fact the renders are usable, just a fraction of a second off in duration.

To elaborate. Here is an example video input and output:

input:
```json
              {
                   "name": "ie_conormacaoidh_gmail_com/shot/464bab8bEadBa9_5ROxEG59qR/original.mp4",
                   "type": "video",
                   "source": "https://s3.amazonaws.com/shotclip-live/ie_conormacaoidh_gmail_com/shot/464bab8bEadBa9_5ROxEG59qR/original.mp4",
                   "required": true
               }
```

output:
```json
               {
                   "path": "ie_conormacaoidh_gmail_com/shot/464bab8bEadBa9_5ROxEG59qR/",
                   "name": "350x180",
                   "extension": "mp4",
                   "dimensions": "350x180",
                   "video_rate": "25",
                   "video_codec": "libx264 -preset veryfast -level 41",
                   "audio_codec": "aac -strict experimental",
                   "video_bitrate": "1000",
                   "audio_bitrate": "64",
                   "required": true,
                   "precision": 0,
                   "type": "video"
               }
```

Any help you can offer is appreciated. But primarily I need to be able to disable the duration check.

Thanks

**Comment by conor-mac-aoidh** [comment]
Or, optionally, adding it as a warning message instead of an error message would be useful.

**Comment by syntropo** [comment]
Commit 637f9e6bc43cb8b371b37fa9c933a4087818d8a3 should correctly support precision values equal to or less than zero. For values less than zero the absolute value is used and if the check fails only a warning is logged. For zero, two durations are equal if they round to the same second. If some values are still failing, please supply them so they can be added to the spec tests.

**Comment by conor-mac-aoidh** [comment]
Thanks for the fix! But there's still an issue. No matter what values I provide for the output precision, 0 is always used. I have verified this by printing the precision as part of the error message. The precision setting must be getting lost somewhere and the default is being used.

**Comment by syntropo** [comment]
Hmm... I'm not able to replicate in the spec tests. The default is zero for audio outputs, but one for video outputs. Could you post the relevant portions of the job JSON?

**Comment by conor-mac-aoidh** [comment]
Precision set to -1 in output:
```
       "outputs": [
           {
               "path": "ie_carlotaduro_gmail_com/shot/6BE999857b97d_39yDPOOoGp/",
               "name": "320x180",
               "extension": "mp4",
               "dimensions": "320x180",
               "video_rate": 20,
               "video_codec": "libx264 -preset veryfast -level 41",
               "audio_codec": "aac -strict experimental",
               "video_bitrate": 1024,
               "audio_bitrate": 256,
               "required": true,
               "precision": -1,
               "type": "video"
           }
       ]
```

Error message returned (with precision printed at the end):

```
generated file with incorrect duration 37.48 != 37.54 or 37.51 /tmp/moviemasher/render/0013fe20-f00b-0132-0814-22000b2417a1/0014aea0-f00b-0132-081b-22000b2417a1.mp3 : precision: 0
```

**Comment by syntropo** [comment]
I have added a precision value of -1 to moviemasher.rb/spec/helpers/media/json/outputs/video_h264.json and a puts statement at line 42 of moviemasher.rb/lib/util/shell_helper.rb. Running the spec tests with the following command from the project directory correctly outputs the precision as negative one:

docker run -it --rm -v $(pwd):/mnt/moviemasher.rb -v $(pwd)/../angular-moviemasher:/mnt/angular-moviemasher moviemasher/moviemasher.rb:local rspec spec/201_render_spec.rb

How are you testing this?

**Comment by conor-mac-aoidh** [comment]
I'm testing this using our test setup which is nearly identical to a production setup - SQS queue & Moviemasher AMI.

I've sent you more details of my tests via email as it contains some sensitive information.

**Comment by syntropo** [comment]
Well, the precision is only being set for one of the outputs. It's the mp3 output that's triggering the error and it has no precision set, so you're getting zero - the default for audio outputs.

**Comment by conor-mac-aoidh** [comment]
Oh - missed that! Working as expected now. Thanks!
