### ISSUE TITLE
Audible pop at begining of rendered videos

### ISSUE THREAD

**Issue by conor-mac-aoidh** [moviemasher/moviemasher.rb#6]
There is a distinctive pop sound at the start of all rendered videos with MM.

Here is an example input/output:

```json
              {
                   "name": "ie_conormacaoidh_gmail_com/shot/D4DE9d94E7AEee_A1vAOQ2V89/original.mp4",
                   "type": "video",
                   "source": "https://s3.amazonaws.com/shotclip-live/ie_conormacaoidh_gmail_com/shot/D4DE9d94E7AEee_A1vAOQ2V89/original.mp4",
                   "required": true
               }
```

```json
               {
                   "path": "ie_conormacaoidh_gmail_com/shot/D4DE9d94E7AEee_A1vAOQ2V89",
                   "name": "350x180",
                   "extension": "mp4",
                   "dimensions": "350x180",
                   "video_rate": "25",
                   "video_codec": "libx264 -preset veryfast -level 41",
                   "audio_codec": "aac -strict experimental",
                   "video_bitrate": "1000",
                   "audio_bitrate": "128",
                   "required": true,
                   "precision": 0,
                   "type": "video"
               }
```

The output video is located here:

https://shotclip-live.s3.amazonaws.com/ie_conormacaoidh_gmail_com/shot/D4DE9d94E7AEee_A1vAOQ2V89/350x180.mp4

The pop sound is noticable at the very start of the clip. I increased the audio bitrate further to 384kbps, which made the pop sound not as loud, but still present.

Any ideas what is causing this?

It's not a massive problem for single clips. But, when multiple clips are combined into a mash, you end up with pops between every clip.

Thanks

**Comment by syntropo** [comment]
Fixed in b3fc383a358d675c27f99a66d04cf1326554cb89

We were still errantly supplying hinting to ecasound suggesting the WAV files were in RAW format, but now we render them in FFmpeg which gives us headers.
