### ISSUE TITLE
Process sqs queue in docker issue

### ISSUE THREAD

**Issue by fodienne** [moviemasher/moviemasher.rb#7]
Hi 

I'm trying to use the Docker command line to pull an SQS job as follow:
docker run -it --rm moviemasher/moviemasher.rb process_one --queue_url=[URL]  --aws_access_key_id=[ID] --aws_secret_access_key=[SECRET]

I'm getting an invalid option from parse for aws_access_key_id. When looking at docker run -it --rm moviemasher/moviemasher.rb process_one --help, the key and secret key options are not specified.

Is there anything else I should do?

**Comment by conor-mac-aoidh** [comment]
I had the same issue running with docker. A workaround is to create an AWS
policy document for the instance, granting it access to all the resources
you need (sqs, s3 etc) without needing a secret key.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policy-structure.html#policy-syntax

**Comment by syntropo** [comment]
Thanks for that, Conor! I'm just realizing it was a mistake to remove the aws_ defaults and descriptions in lib/constant/configuration.rb - I was hoping to avoid having to define them for each service, now that there are more of them. We're using OptionParser here, which seems to insist on predefining all options - grrr. Will look into what would be involved in having the services initialize options at startup... Thanks...

**Comment by fodienne** [comment]
Thanks Conor, I added a policy on my sqs queue but if I call docker run -it --rm moviemasher/moviemasher.rb process_one --queue_url=[URL] without the keys, it throws an error asking for credentials. Do you have another way to call it without credentials?

**Comment by conor-mac-aoidh** [comment]
I don't have another way. But adding a role for that instance should work. Here's how I did it:

- in AWS Managerment Console, go to Security Credentials -> Roles
- add new role called "MovieMasher"
- Choose Role Type: AWS Services Roles, Choose:  Amazon EC2
- When you get to the Attach Policy section, choose AdministratorAccess (or individually select the resources you want access to)

This will create the role/policy you need to get going. Now, when you are configuring your AWS instance, use the IAM role you just created called "MovieMasher" and your instance should have access to SQS, S3 etc.

Hope this helps!

**Comment by fodienne** [comment]
Thanks, but that seem to apply to an AWS instance. My scenario was to use moviemasher.rb locally in docker. I can open up the policy on the SQS queue but the docker process queue script still requires credentials and can't manage them.

**Comment by conor-mac-aoidh** [comment]
Yes that's right it won't work locally. Sorry, I assumed you were running on EC2 since you are using SQS.

**Comment by conor-mac-aoidh** [comment]
You could also try setting the `MOVIEMASHER_CONFIG` environment variable as described here:

https://registry.hub.docker.com/u/moviemasher/moviemasher.rb/

**Comment by syntropo** [comment]
I've added the aws_* config options back in commit faf2efa225fb747a023b205d1d8ea8ebea0e08c9

**Comment by fodienne** [comment]
Just updated the docker image but I'm still getting invalid option error. Is it passing the option test for you?

**Comment by syntropo** [comment]
Are you sure it was updated? I've found sometimes I need to delete the old image in docker or explicitly pull the new one in.

**Comment by fodienne** [comment]
I'm new to docker but I don't think this is my system. I removed the container yesterday. Today I deleted the entire VM and rebuilt it and it's still the same. Have you tested it on your end?

**Comment by syntropo** [comment]
Okay, thanks for the update. I have not had a chance to test, but hope to later today...

**Comment by syntropo** [comment]
Ah, okay... seems we also needed, but never had, defaults for those keys as well. Commit 322c3fd024ded568fac781189c92aa04ca1350c4 adds them - the docker image should auto-build shortly...

**Comment by conor-mac-aoidh** [comment]
Just realised today, when I re-deployed the latest MM image with docker, that this patch breaks my previous configuration. Now, if no access/secret key is defined, MM attempts to use the default value and fails with this error:

```
[ec2-user@ip-10-203-143-215 ~]$ sudo docker run -it --rm moviemasher/moviemasher.rb process_one --queue_url=https://sqs.us-east-1.amazonaws.com/XXX/queue-name
loading configuration file /mnt/moviemasher.rb/config/docker/config.yml
queue_url = https://sqs.us-east-1.amazonaws.com/XXX/queue-name
2015-06-25 10:02:08 +0000 MovieMasher version 4.0.12
process_queues once
/usr/local/bundle/gems/aws-sdk-1.35.0/lib/aws/core/client.rb:374:in `return_or_raise': The security token included in the request is invalid. (AWS::SQS::Errors::InvalidClientTokenId)
        from /usr/local/bundle/gems/aws-sdk-1.35.0/lib/aws/core/client.rb:475:in `client_request'
        from (eval):3:in `receive_message'
        from /usr/local/bundle/gems/aws-sdk-1.35.0/lib/aws/sqs/queue.rb:193:in `receive_message'
        from /mnt/moviemasher.rb/service/queue/sqs.rb:36:in `receive_job'
        from /mnt/moviemasher.rb/lib/moviemasher.rb:173:in `block in process_queues'
        from /mnt/moviemasher.rb/lib/moviemasher.rb:172:in `each'
        from /mnt/moviemasher.rb/lib/moviemasher.rb:172:in `process_queues'
        from config/docker/entrypoint.rb:24:in `<main>'
```

If the access/secret keys are not specified this request should succeed as I am using IAM role based authentication. Could it be that empty values are being supplied here, causing the request to fail?

**Comment by syntropo** [comment]
Ah, you're right. Commit c049257e35c222257f3c8bcd59f9a75f572abd14 should fix this - the docker image should be updated shortly. 

Also realizing that the aws_* configuration options are not yet being used for S3 storage authentication, which might have tripped up fodienne as well?

**Comment by conor-mac-aoidh** [comment]
FYI the docker image has an error:

https://registry.hub.docker.com/u/moviemasher/moviemasher.rb/builds_history/91080/

Might be a good idea to tag images before releasing a new one? Will enable users to fallback to older images

**Comment by syntropo** [comment]
Hmm... not sure why that build failed - retriggering another seemed to work. I will look into assigning a version tag as well... I guess it should match the version of moviemasher.rb, but I haven't been good about updating that each time I push changes.

**Comment by syntropo** [comment]
For the record, the versioning of docker images that are automatically built sucks! I essentially need to trigger three builds in docker hub for each new version because a build must be triggered each time you save the tags - grrr. It does seem to work though... we now have tags for 4.0.12 and 4.0.13 (which is currently also the latest).
