### ISSUE TITLE
Handshake failure error

### ISSUE THREAD

**Issue by uche40** [moviemasher/moviemasher.rb#8]
Hey Doug, I know this issue probably does not belong here, so i apologize.  but the 3x issue tracker was closed to new requests. I was wondering what your thoughts were on a SQS handshake failure error i keep getting when i try to publish a mash. I have included screenshot.

![video jac handshake error-3](https://cloud.githubusercontent.com/assets/8086604/8262666/8b60a028-1699-11e5-841c-c58a2f786076.PNG)

**Comment by syntropo** [comment]
Yes, SQS now no longer supports SSL version 3, which version 3 of Movie Masher uses. In the SDK you can go into httputils.php and comment out the line that sets CURLOPT_SSLVERSION. There is a new AMI (version 3.2.31) which fixes the same file in the Transcoder.

**Comment by uche40** [comment]
Thanks that fixed it., By the way with the version 4x, does it mean that the transcoder and sdk are basically on the same box, so no need to pay amazon for the extra transcoder instance as in 3x.

**Comment by syntropo** [comment]
While it's possible to run everything on one box, this would likely be unsuitable for production if there are any number of users. Keep in mind that video transcoding is extremely resource intensive!
